# Generated by Django 3.1.2 on 2020-10-21 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChemicalElement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('inventory', models.FloatField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concentration', models.IntegerField()),
                ('ChemicalElement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optimizer.chemicalelement')),
                ('Commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optimizer.commodity')),
            ],
        ),
        migrations.AddField(
            model_name='commodity',
            name='chemical_element',
            field=models.ManyToManyField(through='optimizer.Composition', to='optimizer.ChemicalElement'),
        ),
    ]
