# Generated by Django 3.1.2 on 2020-10-21 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='composition',
            old_name='ChemicalElement',
            new_name='chemical_element',
        ),
        migrations.RenameField(
            model_name='composition',
            old_name='Commodity',
            new_name='commodity',
        ),
    ]
