# Generated by Django 3.1.2 on 2020-10-23 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0002_auto_20201021_1727'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='composition',
            unique_together={('commodity', 'chemical_element')},
        ),
    ]
